/* txtjet directive: jet package="example.compat" class="ComponentTemplate" imports="java.util.List" skeleton="skeletons/eclipse.skeleton" */

/* txtjet include begin: partials/license.jetinc */
/* Generated by the JetForge compatibility corpus. */
/* txtjet include end: partials/license.jetinc */

package generated.compat;

public final class Component {
/*
 * txtjet scriptlet:
 * for (String name : List.of("alpha", "beta")) {
 */

    public static final String txtjet_name_toUpperCase = "txtjet:name";
/*
 * txtjet scriptlet:
 * }
 */

}
