const samples = {
  java: {
    filename: "model.javajet",
    outputName: "Model.java",
    language: "Java output",
    statuses: ["Directive mapped to generated package", "Loop mapped to generated fields", "Expression mapped to field type", "Expression mapped to field name", "Include resolved in workspace"],
    source: [
      ['<%@ jet package="demo.codegen" class="ModelWriter" %>', "mark"],
      ["<% for (Field field : model.fields()) { %>", "code"],
      ["private <%= field.type() %>", "output"],
      ["        <%= field.name() %>;", "output"],
      ['<%@ include file="partials/accessors.jetinc" %>', "mark"]
    ],
    output: [["package demo.codegen;", "mark"], ["private String title;", "output"], ["private int revision;", "output"], ["public String getTitle() {", "code"], ["    return title;", "code"]],
    map: [0, 1, 1, 2, 3],
    preview: `package demo.codegen;

public class Model {
    private String title;
    private int revision;
}`
  },
  html: {
    filename: "card.htmljet", outputName: "card.html", language: "HTML output",
    statuses: ["Directive mapped to document metadata", "Element preserved in output", "Expression mapped to heading", "Include expanded from workspace", "Closing element preserved"],
    source: [['<%@ jet class="CardWriter" %>', "mark"], ['<article class="model-card">', "output"], ['  <h2><%= model.name() %></h2>', "code"], ['  <%@ include file="actions.jetinc" %>', "mark"], ['</article>', "output"]],
    output: [['<!-- generated by CardWriter -->', "muted"], ['<article class="model-card">', "output"], ['  <h2>Invoice</h2>', "output"], ['  <button>Edit</button>', "output"], ['</article>', "output"]], map: [0, 1, 2, 3, 4],
    preview: `<article class="model-card">
    <h2>Invoice</h2>
    <button>Edit</button>
</article>`
  },
  xml: {
    filename: "schema.xmljet", outputName: "schema.xml", language: "XML output",
    statuses: ["Root node preserved", "Loop mapped to generated fields", "Name expression resolved", "Type expression resolved", "Closing node preserved"],
    source: [['<entity name="<%= model.name() %>">', "code"], ['  <% for (Field field : fields) { %>', "mark"], ['  <field name="<%= field.name() %>"', "code"], ['         type="<%= field.type() %>" />', "code"], ['</entity>', "output"]],
    output: [['<entity name="Invoice">', "output"], ['  <field name="title" type="string" />', "output"], ['  <field name="revision" type="integer" />', "output"], ['  <field name="owner" type="string" />', "output"], ['</entity>', "output"]], map: [0, 1, 1, 2, 4],
    preview: `<entity name="Invoice">
    <field name="title" type="string" />
    <field name="revision" type="integer" />
</entity>`
  },
  c: {
    filename: "model.cjet", outputName: "model.h", language: "C output",
    statuses: ["Type declaration preserved", "Loop mapped to struct members", "Type helper evaluated", "Name expression evaluated", "Struct close preserved"],
    source: [["typedef struct {", "output"], ["<% for (Field field : fields) { %>", "mark"], ["    <%= cType(field) %>", "code"], ["    <%= field.name() %>;", "code"], ["} GeneratedModel;", "output"]],
    output: [["typedef struct {", "output"], ["    char *title;", "output"], ["    int revision;", "output"], ["    char *owner;", "output"], ["} GeneratedModel;", "output"]], map: [0, 1, 1, 2, 4],
    preview: `typedef struct {
    char *title;
    int revision;
    char *owner;
} GeneratedModel;`
  },
  python: {
    filename: "model.pythonjet", outputName: "model.py", language: "Python output",
    statuses: ["Class expression mapped", "Initializer preserved", "Loop mapped to assignments", "Field expression evaluated", "Local-only note preserved"],
    source: [["class <%= model.name() %>:", "code"], ["    def __init__(self):", "output"], ["    <% for (Field field : fields) { %>", "mark"], ["        self.<%= field.name() %> = None", "code"], ["    # generated locally", "muted"]],
    output: [["class Invoice:", "output"], ["    def __init__(self):", "output"], ["        self.title = None", "output"], ["        self.revision = None", "output"], ["    # generated locally", "muted"]], map: [0, 1, 2, 3, 4],
    preview: `class Invoice:
    def __init__(self):
        self.title = None
        self.revision = None`
  }
};

const modeOrder = Object.keys(samples);
const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const header = document.querySelector("[data-header]");
const menuToggle = document.querySelector(".menu-toggle");
const sourceCode = document.querySelector("#source-code");
const outputCode = document.querySelector("#output-code");
const demoStatus = document.querySelector("#demo-status");
const demoTabs = [...document.querySelectorAll("[data-demo-mode]")];
const modeTabs = [...document.querySelectorAll("[data-mode]")];
const modeCode = document.querySelector("#mode-code");
const modeFilename = document.querySelector("#mode-filename");
const modeLanguage = document.querySelector("#mode-language");
const demoPanel = document.querySelector("#demo-panel");
const modePanel = document.querySelector("#mode-preview");
const mappingLane = document.querySelector(".mapping-lane");
const toast = document.querySelector(".copy-toast");
const mobileMenu = window.matchMedia("(max-width: 900px)");
let activeDemoMode = "java";
let activeLine = 0;
let cycleTimer = null;

function createLine(text, token, index, interactive) {
  const item = document.createElement("li");
  const line = document.createElement(interactive ? "button" : "span");
  if (interactive) line.type = "button";
  line.className = `code-line token-${token}`;
  line.dataset.line = String(index + 1).padStart(2, "0");
  line.textContent = text;
  if (interactive) {
    line.setAttribute("aria-label", `Trace source line ${index + 1}: ${text}`);
    line.addEventListener("click", () => selectLine(index, true));
  }
  item.append(line);
  return item;
}

function selectLine(index, manual = false) {
  const sample = samples[activeDemoMode];
  activeLine = index % sample.source.length;
  const outputIndex = sample.map[activeLine];
  sourceCode.querySelectorAll(".code-line").forEach((line, lineIndex) => line.classList.toggle("is-active", lineIndex === activeLine));
  outputCode.querySelectorAll(".code-line").forEach((line, lineIndex) => line.classList.toggle("is-active", lineIndex === outputIndex));
  const labels = { java: "Java", html: "HTML", xml: "XML", c: "C", python: "Python" };
  demoStatus.textContent = `${labels[activeDemoMode]} · ${sample.statuses[activeLine]}`;
  mappingLane.style.setProperty("--map-position", `${12 + (outputIndex / Math.max(1, sample.output.length - 1)) * 76}%`);
  if (manual) restartCycle();
}

function setDemoMode(mode, manual = false) {
  if (!samples[mode]) return;
  activeDemoMode = mode;
  const sample = samples[mode];
  sourceCode.replaceChildren(...sample.source.map((line, index) => createLine(line[0], line[1], index, true)));
  outputCode.replaceChildren(...sample.output.map((line, index) => createLine(line[0], line[1], index, false)));
  document.querySelector(".editor-pane header span").textContent = sample.filename;
  document.querySelector(".output-pane header span").textContent = sample.outputName;
  demoTabs.forEach(tab => {
    const selected = tab.dataset.demoMode === mode;
    tab.setAttribute("aria-selected", String(selected));
    tab.tabIndex = selected ? 0 : -1;
  });
  demoPanel.setAttribute("aria-labelledby", `demo-tab-${mode}`);
  selectLine(0, manual);
}

function setModePreview(mode) {
  const sample = samples[mode];
  if (!sample) return;
  modeCode.textContent = sample.preview;
  modeFilename.textContent = sample.filename;
  modeLanguage.textContent = sample.language;
  modeTabs.forEach(tab => {
    const selected = tab.dataset.mode === mode;
    tab.setAttribute("aria-selected", String(selected));
    tab.tabIndex = selected ? 0 : -1;
  });
  modePanel.setAttribute("aria-labelledby", `mode-tab-${mode}`);
}

function restartCycle() {
  if (cycleTimer) window.clearInterval(cycleTimer);
  if (!reduceMotion) cycleTimer = window.setInterval(() => selectLine(activeLine + 1), 2800);
}

function handleTabKeys(event, tabs, attribute, setter) {
  const direction = { ArrowRight: 1, ArrowDown: 1, ArrowLeft: -1, ArrowUp: -1 }[event.key];
  if (!direction) return;
  event.preventDefault();
  const current = tabs.indexOf(event.currentTarget);
  const next = tabs[(current + direction + tabs.length) % tabs.length];
  next.focus();
  setter(next.dataset[attribute]);
}

demoTabs.forEach(tab => {
  tab.addEventListener("click", () => setDemoMode(tab.dataset.demoMode, true));
  tab.addEventListener("keydown", event => handleTabKeys(event, demoTabs, "demoMode", mode => setDemoMode(mode, true)));
});
modeTabs.forEach(tab => {
  tab.addEventListener("click", () => setModePreview(tab.dataset.mode));
  tab.addEventListener("keydown", event => handleTabKeys(event, modeTabs, "mode", setModePreview));
});

function syncMobileMenu() {
  const open = header.classList.contains("menu-open");
  document.querySelector("#site-nav").inert = mobileMenu.matches && !open;
}

menuToggle?.addEventListener("click", () => {
  const open = header.classList.toggle("menu-open");
  menuToggle.setAttribute("aria-expanded", String(open));
  syncMobileMenu();
});
document.querySelectorAll(".site-nav a").forEach(link => link.addEventListener("click", () => {
  header.classList.remove("menu-open");
  menuToggle?.setAttribute("aria-expanded", "false");
  syncMobileMenu();
}));
mobileMenu.addEventListener("change", () => {
  header.classList.remove("menu-open");
  menuToggle?.setAttribute("aria-expanded", "false");
  syncMobileMenu();
});

const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (!entry.isIntersecting) return;
    entry.target.classList.add("is-visible");
    revealObserver.unobserve(entry.target);
  });
}, { threshold: 0.12, rootMargin: "0px 0px -5%" });
document.querySelectorAll(".reveal").forEach(element => reduceMotion ? element.classList.add("is-visible") : revealObserver.observe(element));

const navLinks = [...document.querySelectorAll(".site-nav a")];
const navSections = navLinks.map(link => document.querySelector(link.getAttribute("href"))).filter(Boolean);
const sectionObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (!entry.isIntersecting) return;
    navLinks.forEach(link => link.classList.toggle("is-active", link.getAttribute("href") === `#${entry.target.id}`));
  });
}, { rootMargin: "-25% 0px -65%", threshold: 0 });
navSections.forEach(section => sectionObserver.observe(section));

window.addEventListener("scroll", () => header?.classList.toggle("is-scrolled", window.scrollY > 12), { passive: true });

async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const area = document.createElement("textarea");
    area.value = text;
    area.style.position = "fixed";
    area.style.opacity = "0";
    document.body.append(area);
    area.select();
    document.execCommand("copy");
    area.remove();
  }
  toast.textContent = "Command copied";
  toast.classList.add("is-visible");
  window.setTimeout(() => toast.classList.remove("is-visible"), 1800);
}
document.querySelectorAll("[data-copy]").forEach(button => button.addEventListener("click", () => copyText(button.dataset.copy)));

setDemoMode("java");
setModePreview("java");
syncMobileMenu();
restartCycle();
