const samples = {
  java: {
    label: "Java",
    filename: "model.javajet",
    outputName: "Model.java",
    statuses: ["Directive mapped to generated package", "Loop mapped to generated fields", "Expression mapped to field type", "Expression mapped to field name", "Include resolved in workspace"],
    source: [
      ['<%@ jet package="demo.codegen" class="ModelWriter" %>', "mark"],
      ["<% for (Field field : model.fields()) { %>", "code"],
      ["private <%= field.type() %>", "output"],
      ["        <%= field.name() %>;", "output"],
      ['<%@ include file="partials/accessors.jetinc" %>', "mark"]
    ],
    output: [["package demo.codegen;", "mark"], ["private String title;", "output"], ["private int revision;", "output"], ["public String getTitle() {", "code"], ["    return title;", "code"]],
    map: [0, 1, 1, 2, 3]
  },
  html: {
    label: "HTML",
    filename: "card.htmljet",
    outputName: "card.html",
    statuses: ["Directive mapped to document metadata", "Element preserved in preview", "Expression mapped to heading", "Include expanded from workspace", "Closing element preserved"],
    source: [['<%@ jet class="CardWriter" %>', "mark"], ['<article class="model-card">', "output"], ['  <h2><%= model.name() %></h2>', "code"], ['  <%@ include file="actions.jetinc" %>', "mark"], ['</article>', "output"]],
    output: [['<!-- generated by CardWriter -->', "muted"], ['<article class="model-card">', "output"], ['  <h2>Invoice</h2>', "output"], ['  <button>Edit</button>', "output"], ['</article>', "output"]],
    map: [0, 1, 2, 3, 4]
  },
  xml: {
    label: "XML",
    filename: "schema.xmljet",
    outputName: "schema.xml",
    statuses: ["Root node preserved", "Loop mapped to generated fields", "Name expression resolved", "Type expression resolved", "Closing node preserved"],
    source: [['<entity name="<%= model.name() %>">', "code"], ['  <% for (Field field : fields) { %>', "mark"], ['  <field name="<%= field.name() %>"', "code"], ['         type="<%= field.type() %>" />', "code"], ['</entity>', "output"]],
    output: [['<entity name="Invoice">', "output"], ['  <field name="title" type="string" />', "output"], ['  <field name="revision" type="integer" />', "output"], ['  <field name="owner" type="string" />', "output"], ['</entity>', "output"]],
    map: [0, 1, 1, 2, 4]
  },
  c: {
    label: "C",
    filename: "model.cjet",
    outputName: "model.h",
    statuses: ["Type declaration preserved", "Loop mapped to struct members", "Type helper evaluated", "Name expression evaluated", "Struct close preserved"],
    source: [["typedef struct {", "output"], ["<% for (Field field : fields) { %>", "mark"], ["    <%= cType(field) %>", "code"], ["    <%= field.name() %>;", "code"], ["} GeneratedModel;", "output"]],
    output: [["typedef struct {", "output"], ["    char *title;", "output"], ["    int revision;", "output"], ["    char *owner;", "output"], ["} GeneratedModel;", "output"]],
    map: [0, 1, 1, 2, 4]
  },
  python: {
    label: "Python",
    filename: "model.pythonjet",
    outputName: "model.py",
    statuses: ["Class expression mapped", "Initializer preserved", "Loop mapped to assignments", "Field expression evaluated", "Local-only note preserved"],
    source: [["class <%= model.name() %>:", "code"], ["    def __init__(self):", "output"], ["    <% for (Field field : fields) { %>", "mark"], ["        self.<%= field.name() %> = None", "code"], ["    # generated locally", "muted"]],
    output: [["class Invoice:", "output"], ["    def __init__(self):", "output"], ["        self.title = None", "output"], ["        self.revision = None", "output"], ["    # generated locally", "muted"]],
    map: [0, 1, 2, 3, 4]
  },
  latex: {
    label: "LaTeX",
    filename: "report.latexjet",
    outputName: "report.tex",
    statuses: ["Document class expression mapped", "Loop mapped to generated sections", "Title expression mapped", "Body expression mapped", "Template loop close mapped"],
    source: [["\\documentclass{<%= model.documentClass() %>}", "code"], ["<% for (Section section : model.sections()) { %>", "mark"], ["\\section{<%= section.title() %>}", "code"], ["<%= section.body() %>", "output"], ["<% } %>", "mark"]],
    output: [["\\documentclass{article}", "output"], ["\\begin{document}", "output"], ["\\section{Overview}", "output"], ["Generated locally from the model.", "output"], ["\\end{document}", "output"]],
    map: [0, 2, 2, 3, 4]
  }
};

function createLine(text, token, index, interactive) {
  const item = document.createElement("li");
  const line = document.createElement(interactive ? "button" : "span");
  if (interactive) line.type = "button";
  line.className = `code-line token-${token}`;
  line.dataset.line = String(index + 1).padStart(2, "0");
  line.textContent = text;
  if (interactive) {
    line.setAttribute("aria-label", `Trace source line ${index + 1}: ${text}`);
    line.setAttribute("aria-pressed", "false");
  }
  item.append(line);
  return item;
}

function initWorkbench() {
  const workbench = document.querySelector(".workbench");
  const sourceCode = document.querySelector("#source-code");
  const outputCode = document.querySelector("#output-code");
  const demoStatus = document.querySelector("#demo-status");
  const demoPanel = document.querySelector("#demo-panel");
  const mappingLane = document.querySelector(".mapping-lane");
  const sourceName = document.querySelector(".source-pane header span");
  const outputName = document.querySelector(".output-pane header span");
  const tabs = [...document.querySelectorAll("[data-demo-mode]")];
  if (!workbench || !sourceCode || !outputCode || !demoStatus || !demoPanel || !mappingLane || !sourceName || !outputName || !tabs.length) return;

  let activeMode = "java";

  function selectLine(index) {
    const sample = samples[activeMode];
    const activeLine = Math.max(0, Math.min(index, sample.source.length - 1));
    const outputIndex = sample.map[activeLine];

    sourceCode.querySelectorAll(".code-line").forEach((line, lineIndex) => {
      const selected = lineIndex === activeLine;
      line.classList.toggle("is-active", selected);
      line.setAttribute("aria-pressed", String(selected));
    });
    outputCode.querySelectorAll(".code-line").forEach((line, lineIndex) => {
      const selected = lineIndex === outputIndex;
      line.classList.toggle("is-active", selected);
      if (selected) line.setAttribute("aria-current", "true");
      else line.removeAttribute("aria-current");
    });

    if (Number.isInteger(outputIndex)) {
      demoStatus.textContent = `${sample.label} · Source line ${activeLine + 1} maps to local preview line ${outputIndex + 1}: ${sample.statuses[activeLine]}`;
      mappingLane.style.setProperty("--map-position", `${12 + (outputIndex / Math.max(1, sample.output.length - 1)) * 76}%`);
    } else {
      demoStatus.textContent = `${sample.label} · Source line ${activeLine + 1} has no deterministic preview range`;
      mappingLane.style.setProperty("--map-position", "50%");
    }
  }

  function setMode(mode) {
    const sample = samples[mode];
    if (!sample) return;
    activeMode = mode;
    sourceCode.replaceChildren(...sample.source.map((line, index) => createLine(line[0], line[1], index, true)));
    outputCode.replaceChildren(...sample.output.map((line, index) => createLine(line[0], line[1], index, false)));
    sourceName.textContent = sample.filename;
    outputName.textContent = sample.outputName;
    tabs.forEach(tab => {
      const selected = tab.dataset.demoMode === mode;
      tab.setAttribute("aria-selected", String(selected));
      tab.tabIndex = selected ? 0 : -1;
    });
    demoPanel.setAttribute("aria-labelledby", `demo-tab-${mode}`);
    selectLine(0);
  }

  function handleTabKey(event) {
    const current = tabs.indexOf(event.currentTarget);
    let nextIndex;
    if (["ArrowRight", "ArrowDown"].includes(event.key)) nextIndex = (current + 1) % tabs.length;
    else if (["ArrowLeft", "ArrowUp"].includes(event.key)) nextIndex = (current - 1 + tabs.length) % tabs.length;
    else if (event.key === "Home") nextIndex = 0;
    else if (event.key === "End") nextIndex = tabs.length - 1;
    else return;
    event.preventDefault();
    const next = tabs[nextIndex];
    next.focus();
    setMode(next.dataset.demoMode);
  }

  sourceCode.addEventListener("click", event => {
    const line = event.target instanceof Element ? event.target.closest("button.code-line") : null;
    if (line) selectLine(Number.parseInt(line.dataset.line, 10) - 1);
  });
  tabs.forEach(tab => {
    tab.addEventListener("click", () => setMode(tab.dataset.demoMode));
    tab.addEventListener("keydown", handleTabKey);
  });
  setMode("java");
  workbench.classList.add("is-ready");
}

function initMenu() {
  const header = document.querySelector("[data-header]");
  const toggle = document.querySelector(".menu-toggle");
  const navShell = document.querySelector("#site-nav");
  if (!header || !toggle || !navShell) return;
  const mobileMenu = window.matchMedia("(max-width: 1080px)");
  const fallbackFocusables = "inert" in navShell ? [] : [...navShell.querySelectorAll("a, button")];

  function setFallbackTabOrder(disabled) {
    fallbackFocusables.forEach(element => {
      if (disabled) element.setAttribute("tabindex", "-1");
      else element.removeAttribute("tabindex");
    });
  }

  function syncMenu() {
    const closed = mobileMenu.matches && !header.classList.contains("menu-open");
    if ("inert" in navShell) navShell.inert = closed;
    else setFallbackTabOrder(closed);
    if (closed) navShell.setAttribute("aria-hidden", "true");
    else navShell.removeAttribute("aria-hidden");
  }

  function closeMenu({ restoreFocus = false } = {}) {
    header.classList.remove("menu-open");
    toggle.setAttribute("aria-expanded", "false");
    syncMenu();
    if (restoreFocus) toggle.focus();
  }

  toggle.addEventListener("click", () => {
    const open = header.classList.toggle("menu-open");
    toggle.setAttribute("aria-expanded", String(open));
    syncMenu();
  });
  document.addEventListener("keydown", event => {
    if (event.key === "Escape" && header.classList.contains("menu-open")) closeMenu({ restoreFocus: true });
  });
  navShell.querySelectorAll("a").forEach(link => link.addEventListener("click", () => closeMenu()));
  mobileMenu.addEventListener("change", () => closeMenu());
  syncMenu();
  document.documentElement.classList.add("menu-ready");
}

function initReveal() {
  const elements = [...document.querySelectorAll(".reveal")];
  const motion = window.matchMedia("(prefers-reduced-motion: reduce)");
  if (!elements.length || motion.matches || !("IntersectionObserver" in window)) {
    elements.forEach(element => element.classList.add("is-visible"));
    return;
  }

  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add("is-visible");
      observer.unobserve(entry.target);
    });
  }, { threshold: 0.1, rootMargin: "0px 0px -4%" });

  elements.forEach(element => {
    const bounds = element.getBoundingClientRect();
    if (bounds.bottom > 0 && bounds.top < window.innerHeight * .95) element.classList.add("is-visible");
    else {
      element.classList.add("will-reveal");
      observer.observe(element);
    }
  });

  motion.addEventListener("change", event => {
    if (!event.matches) return;
    elements.forEach(element => element.classList.add("is-visible"));
    observer.disconnect();
  }, { once: true });
}

function initActiveNavigation() {
  const links = [...document.querySelectorAll(".site-nav a[href^='#']")];
  const sections = links.map(link => document.querySelector(link.getAttribute("href"))).filter(Boolean);
  if (!links.length || !sections.length || !("IntersectionObserver" in window)) return;

  function setActive(id) {
    links.forEach(link => {
      const active = link.getAttribute("href") === `#${id}`;
      link.classList.toggle("is-active", active);
      if (active) link.setAttribute("aria-current", "location");
      else link.removeAttribute("aria-current");
    });
  }

  const observer = new IntersectionObserver(entries => {
    const visible = entries.filter(entry => entry.isIntersecting).sort((a, b) => Math.abs(a.boundingClientRect.top) - Math.abs(b.boundingClientRect.top));
    if (visible[0]) setActive(visible[0].target.id);
  }, { rootMargin: "-24% 0px -66%", threshold: 0 });
  sections.forEach(section => observer.observe(section));
}

function initHeaderState() {
  const header = document.querySelector("[data-header]");
  if (!header) return;
  function update() {
    header.classList.toggle("is-scrolled", window.scrollY > 12);
  }
  update();
  window.addEventListener("scroll", update, { passive: true });
}

[initWorkbench, initMenu, initReveal, initActiveNavigation, initHeaderState].forEach(initialize => {
  try {
    initialize();
  } catch (error) {
    console.error(`JetForge enhancement failed in ${initialize.name}`, error);
  }
});
